# Ce fichier vient surcharger notre docker-compose.yml pour le dev
services:
  # On surcharge le service Symfony
  symfony:
    build:
      # On lui dit d'utiliser notre nouveau Dockerfile de dev
      context: ./Iris-Gestion-Back
      dockerfile: Dockerfile.dev
    environment:
      # On s'assure d'être en mode dev
      APP_ENV: dev
      # On active Xdebug
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    volumes:
      # C'est la ligne la plus importante :
      # Elle monte TOUT le code du backend dans le conteneur.
      # Toute modification sur votre PC sera instantanée dans le conteneur.
      - ./Iris-Gestion-Back:/var/www/html

  # On surcharge le service Nginx pour le dev
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      # On expose Nginx sur le port 8080 pour éviter les conflits
      # avec d'autres serveurs qui pourraient tourner sur votre PC
      - "8088:80"

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./Iris-Gestion-Front:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"