parameters:
    # On déclare ici les variables d'environnement que notre application utilise
    # pour que le conteneur de services de Symfony en soit conscient.
    env(JWT_PASSPHRASE): ''
    app.sender_email: 'honfleur@youandeyephoto.com'
    app.sender_name: 'You & Eye Photo - Honfleur'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $piwigoUrl: 'https://www.galeries.mehdiabakri.fr'
            $piwigoUser: '3qg4b'
            $piwigoPassword: 's%4#FbOc$F'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DataFixtures/DevFixtures.php'

    App\Service\EmailSender:
        arguments:
            $senderEmail: '%app.sender_email%'
            $senderName: '%app.sender_name%'