parameters:
    # On déclare ici les variables d'environnement que notre application utilise
    # pour que le conteneur de services de Symfony en soit conscient.
    env(JWT_PASSPHRASE): ''
    app.sender_email: 'honfleur@youandeyephoto.com'
    app.sender_name: 'You & Eye Photo - Honfleur'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DataFixtures/DevFixtures.php'

        tags: ['controller.service_arguments']

    App\Service\EmailSender:
        arguments:
            $senderEmail: '%app.sender_email%'
            $senderName: '%app.sender_name%'