parameters:
    # On déclare ici les variables d'environnement que notre application utilise
    # pour que le conteneur de services de Symfony en soit conscient.
    env(JWT_PASSPHRASE): ''
    app.sender_email: 'honfleur@youandeyephoto.com'
    app.sender_name: 'You & Eye Photo - Honfleur'
    env(CLOUDINARY_CLOUD_NAME): 'dyjhgjwir'
    env(CLOUDINARY_URL): 'cloudinary://353942736124422:k2__UsJbE09dR1JyvIYj5VQOWA0@dyjhgjwir'

services:
    _defaults:
        autowire: true
        autoconfigure: true

        bind:
            $cloudinaryUrl: '%env(CLOUDINARY_URL)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/DataFixtures/DevFixtures.php'

    App\Service\EmailSender:
        arguments:
            $senderEmail: '%app.sender_email%'
            $senderName: '%app.sender_name%'